# This is a template for secrets - actual values should be provided via Sealed Secrets
apiVersion: v1
kind: Secret
metadata:
  name: selin-secrets
  namespace: selin
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded credentials
  postgres-user: cG9zdGdyZXM=                    # "postgres"
  postgres-password: Y2hhbmdlbWVwbGVhc2U=         # "changmeplease"
  redis-password: cmVkaXNwYXNzd29yZA==            # "redispassword"
  api-token: YXBpLXRva2VuLWNoYW5nZS1tZQ==        # "api-token-change-me"
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleQ==   # "your-openai-api-key"
  claude-api-key: eW91ci1jbGF1ZGUtYXBpLWtleQ==   # "your-claude-api-key"
---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: selin-config
  namespace: selin
data:
  app.yaml: |
    server:
      port: 8080
      timeout: 30s
    
    rate_limiting:
      user_requests_per_minute: 60
      collector_requests_per_minute: 120
    
    database:
      host: postgresql
      port: 5432
      name: selin
      max_connections: 20
    
    redis:
      host: redis
      port: 6379
      db: 0
    
    weaviate:
      host: weaviate
      port: 8080
      scheme: http
    
    logging:
      level: info
      format: json
    
    monitoring:
      enabled: true
      metrics_port: 9090
