apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: selin-nfs-pvc
  namespace: selin
  labels:
    app: selin-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-storage
