# Collection and Processing Schedules for Selin
# This file controls when different jobs run and how frequently

data_collection:
  reddit_collector:
    schedule: "*/5 * * * *"  # Every 5 minutes
    timezone: "UTC"
    enabled: true
    
  twitter_collector:
    schedule: "*/10 * * * *"  # Every 10 minutes
    timezone: "UTC"
    enabled: true
    
  github_collector:
    schedule: "*/30 * * * *"  # Every 30 minutes
    timezone: "UTC"
    enabled: true
    
  file_watcher:
    schedule: "*/1 * * * *"  # Every minute
    timezone: "UTC"
    enabled: true

data_processing:
  content_processor:
    schedule: "*/15 * * * *"  # Every 15 minutes
    timezone: "UTC"
    batch_size: 100
    enabled: true
    
  vector_generator:
    schedule: "*/20 * * * *"  # Every 20 minutes
    timezone: "UTC"
    batch_size: 50
    enabled: true
    
  concept_mapper:
    schedule: "0 */2 * * *"  # Every 2 hours
    timezone: "UTC"
    enabled: true

batch_jobs:
  daily_processor:
    schedule: "0 2 * * *"  # Daily at 2 AM
    timezone: "UTC"
    enabled: true
    tasks:
      - "aggregate_daily_stats"
      - "cleanup_old_data"
      - "update_learning_metrics"
    
  weekly_analyzer:
    schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM
    timezone: "UTC"
    enabled: true
    tasks:
      - "generate_learning_report"
      - "update_learning_paths"
      - "analyze_progress"
    
  backup_service:
    schedule: "0 4 * * *"  # Daily at 4 AM
    timezone: "UTC"
    enabled: true
    retention_days: 30
